#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppTest.Resource", IsApplication=true)]

namespace AppTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FingerprintAuth.Resource.String.key = global::AppTest.Resource.String.key;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int btn_fingerprint = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int activity_main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int app_name = 2130903041;
			
			// aapt resource value: 0x7f030006
			public const int auth_failed = 2130903046;
			
			// aapt resource value: 0x7f030005
			public const int auth_succeeded = 2130903045;
			
			// aapt resource value: 0x7f030002
			public const int button_fingerprint_text = 2130903042;
			
			// aapt resource value: 0x7f030004
			public const int dialog_fingerprint_message = 2130903044;
			
			// aapt resource value: 0x7f030003
			public const int dialog_fingerprint_title = 2130903043;
			
			// aapt resource value: 0x7f030000
			public const int key = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
